### ISSUE TITLE
Can't use normal Nether Portals

### ISSUE THREAD

**Issue by notMateo** [McCraftaholics/Bukkit-WarpPortals#23]
I'mma use Bukkit's thingy, because I originally was going to post this to Multiworld's tickets, but this seems more of an issue here.

What steps will reproduce the problem?
1. Trying to go through any STANDARD Nether Portal. WarpPortals function normally
2. 
3.

What is the expected output? What do you see instead?
To be transported to that worlds linked Nether, since we have multiple words with Multiworld

What version of the product are you using?
v0563, I believe

What version of the craftbukkit/bukkit are you using?
1.7.9, Bukkit build #3080

Do you have an error log of what happened?
Unfortunately, not.

I'm willing to supply any information or test anything you deem necessary, just please help us before our server opens back up in a month. Also, I will be updating this ticket in some time, after I test something out myself.

**Comment by awendland** [comment]
This bug should be fixed by 45feddfb824b9aefee4262c556cd7767dd779b7e
