### ISSUE TITLE
Portals misaligned?

### ISSUE THREAD

**Issue by Uskaanax** [McCraftaholics/Bukkit-WarpPortals#33]
These used to  be aligned until I upgraded the server to 1.8+ (currently running CraftBukkit version git-Spigot-4c7d0c0-7d020a7 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)). Is this a known bug or something unique? I've tried deleting the portal and recreating it with a new name and it still gives the same result.

My jar is a little old, downloaded Nov 26. The page http://dev.bukkit.org/bukkit-plugins/warp-portals/ doesn't  list any update since 2013. Is this a dead project?

![2015-04-09_00 20 22](https://cloud.githubusercontent.com/assets/11241379/7061431/11024b56-de4f-11e4-8407-763c3d3bf950.png)

**Comment by awendland** [comment]
This problem has been addressed on the analytics branch of this repository. You can find a test version that has the fix at http://dev.bukkit.org/bukkit-plugins/warp-portals/?comment=310. A release version with the change will ideally come out in the next several weeks.

**Comment by awendland** [comment]
Closed by d10633b8d5010dcb08a8bb3aa0df9faf5d10db31

**Comment by Uskaanax** [comment]
Thanks for the quick response!
